name: Sahi Buzz Scraper

on:
  schedule:
    - cron: '0 16 * * *'  # 4:00 PM UTC daily
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install puppeteer

      - name: Run scraping script
        run: node scrape.js > output.json
        env:
          NODE_OPTIONS: --unhandled-rejections=strict

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: sahi-buzz-results
          path: output.json
