name: Daily Sahi Buzz Scraper

on:
  schedule:
    - cron: '0 16 * * *'  # 4:00 PM UTC daily
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install puppeteer@21.11.0
          sudo apt-get update
          sudo apt-get install -y libgbm-dev wget

      - name: Install Chrome for Puppeteer
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          rm google-chrome-stable_current_amd64.deb

      - name: Run scraping script
        run: node scrape.js > output.log 2>&1
        env:
          NODE_OPTIONS: --unhandled-rejections=strict
          PUPPETEER_EXECUTABLE_PATH: '/usr/bin/google-chrome'

      - name: Show logs
        run: cat output.log

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: sahi-buzz-results
          path: |
            output.json
            output.log